Optional learning parser
mitre/caldera pull request #2105
Opened 2021-04-06 16:05 UTC by uruwhy

## Description
Create new operation option to enable/disable learning parsers for the operation. Users can toggle the option via GUI menu under the "Autonomous" options section.  Learning parsers will be disabled by default for the operation.

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?
Created tests to make sure that new facts are generated when learning parsers are enabled and given proper input, and that new facts are not generated when learning parsers are disabled.

Also tested by manually running operations with the option enabled and disabled.

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2021-04-06 17:26 UTC, wbooth requested changes
request: default to using the learning parsers to make this a nonbreaking change. 

suggestion: Also calling them just 'default' parsers may be less confusing than 'learning' parsers. I'm hesitant to introduce a new term to the front end, but technically its accurate

2021-04-06 18:23 UTC, uruwhy commented
> request: default to using the learning parsers to make this a nonbreaking change.
> 
> suggestion: Also calling them just 'default' parsers may be less confusing than 'learning' parsers. I'm hesitant to introduce a new term to the front end, but technically its accurate

Made both changes!

2021-04-07 16:05 UTC, protoli approved these changes

2021-04-07 19:24 UTC, wbooth approved these changes

2021-04-08 18:30 UTC, merged