virts-1872
mitre/caldera pull request #2135
Opened 2021-04-21 20:11 UTC by ArtificialErmine

## Description

Adds the ability for Caldera to run 'recovery' actions, if an agent dies. The specific process is this:

1) An agent dies
2) Caldera detects the agent dies, and if the operation is configured to do so (which is the default), it will process the existing chain of links to see if any use a fact that includes the host of the dead agent. 
3) If matches were found, the system will create new versions of these matches, assuming this is the first time it has done so (repeat failures are ignored).
4) A new agent spawns on the host the previous agent died on. 

This system runs actively during the operation, but is suppressed during cleanup, for obvious reasons. There are also various cleanup tweaks present in this merge request for formatting and compatibility reasons. 

Associated stockpile changes here - https://github.com/mitre/stockpile/pull/527

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

These changes have been tested using an AWS environment and the Alice adversary, as well as with a collection of new tests.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [] I have made corresponding changes to the documentation (Not yet - curious to what degree we want to document this - it's largely self contained and invisible to users outside of the one new field)
- [X] I have added tests that prove my fix is effective or that my feature works

2021-04-26 00:20 UTC, clenk requested changes
- Did you mean to remove the `timeout` parameter from `Operation.__init__` and `RestService._build_operation_object`?

- Any reason to not add `enable_recovery` to `OperationSchema`?

- Same question for `recovery` and `LinkSchema`.

- For documentation, we should at least mention the recover option [here](https://caldera.readthedocs.io/en/latest/Basic-Usage.html#operations).

2021-04-26 00:20 UTC, clenk commented on tests/services/test_planning_svc.py
> +        # null out values un-synced values in the output
```suggestion
        # null out un-synced values in the output
```

2021-04-26 14:15 UTC, wbooth requested changes
Let's chat about this implementation

2021-04-27 20:42 UTC, elegantmoose commented on app/utility/base_planning_svc.py
> +            potential_links = [x for x in potential_links if x not in previous_recovs]
+1 - if `_get_potential_recovery_links()` is or will not be used elsewhere where all potential links are needed

2021-04-27 21:12 UTC, ArtificialErmine commented
Closing in favor of moving this code to other locations.

2021-04-27 21:12 UTC, closed without merging