WIP [VIRTS-1998] Config API v2
mitre/caldera pull request #2149
Opened 2021-05-06 21:44 UTC by bworrell

## Description
Added an API for configuration and other helpful utilities.

* Sensitive configuration items (users, keys, passwords, etc.) are filtered out of responses and/or rejected in requests.
* Responses are just generic JSON documents w/ variable keys (we might want to change this).

## New endpoints:
* `GET /api/v2/config/:name`
  * Returns the entire configuration matching `name` (e.g., `main` or `agents`).
* `PATCH /api/v2/config/main` 
  * Update the `main` configuration
* `PATCH `/api/v2/config/agents`
  * Update the `agents` configuration   

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Working on this....

* Confirmed endpoints appear in swagger documentation
* Confirmed that endpoints return 401 if not authenticated
* Hit the endpoints in Postman w/ api key auth (i'll write more about this).

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-05-11 14:04 UTC, bworrell commented on app/api/v2/managers/config_api_manager.py
> +        if sleep_min is not None:
I don't like that we don't perform any validation on these values (aside from the datatype validation performed by marshmallow). I am gonna add some validation--just need to decide where the best place is do do that

2021-05-12 14:06 UTC, b17zr requested changes
Looks really good! I only have nits on quotes.

2021-05-12 14:24 UTC, bworrell commented on tests/api/v2/test_validation.py
> +        validation.check_not_empty_string("")
I'll update that!

2021-05-12 14:24 UTC, bworrell commented on tests/api/v2/managers/test_config_api_manager.py
> +        await manager.update_global_agent_config(implant_name="")
![image](https://user-images.githubusercontent.com/2118633/117991680-472c5800-b30c-11eb-9525-1725aafe4ee2.png)

2021-05-12 14:25 UTC, bworrell commented on tests/api/v2/managers/test_config_api_manager.py
> +        await manager.update_global_agent_config(implant_name="")
i'll fix it :D

2021-05-12 19:32 UTC, b17zr submitted a review, later dismissed
LGTM!

2021-05-18 17:33 UTC, wbooth commented on app/api/v2/managers/config_api_manager.py
> +    'app.contact.tunnel.ssh.user_password',
drop app.contact

2021-05-18 17:35 UTC, wbooth commented on app/api/v2/managers/config_api_manager.py
> +    'ability_refresh',
drop ability_refresh?

2021-05-18 18:33 UTC, b17zr approved these changes

2021-05-24 17:46 UTC, wbooth approved these changes

2021-05-24 17:47 UTC, merged