[VIRTS-1868] Consolidate support for XORED file operations
mitre/caldera pull request #2158
Opened 2021-05-17 12:40 UTC by emmanvg

## Description

Refactors areas of code that relates to .xored file operations. Broken down independent operations (add, check, remove) and moved relevant code to the File Service. The method `walk_file_path` was moved to the File Service as part of this refactor.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Wrote new tests for the new FileSvc methods. On the UI, open adversaries, select an ability and look for any payloads that would be xored. Check their display names do not contain the .xored extension.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

2021-05-18 14:47 UTC, clenk requested changes
Tested by running an operation with an xored payload; ran successfully.

2021-05-18 15:35 UTC, emmanvg commented on app/service/file_svc.py
> +        if self.is_extension_xored(file_path):
Good point.

2021-05-18 15:36 UTC, emmanvg commented on app/utility/base_world.py
> -    async def walk_file_path(path, target):
Good point.

2021-05-18 19:43 UTC, emmanvg commented on app/service/file_svc.py
> +        if self.is_extension_xored(file_path):
resolved

2021-05-18 19:44 UTC, emmanvg commented on app/utility/base_world.py
> -    async def walk_file_path(path, target):
To make this possible while supporting the other areas where it gets used I moved the methods back to BaseWorld since it spans objects and services.

2021-05-24 18:48 UTC, clenk approved these changes

2021-05-25 12:57 UTC, uruwhy approved these changes
Looks good to me!

2021-05-25 15:59 UTC, merged