VIRTS-2492 Implement _get_fact_origin
mitre/caldera pull request #2195
Opened 2021-07-07 19:27 UTC by copsahl

## Description

Implemented `_get_fact_origin()` function in `base_knowledge_svc.py`. This function takes in either a Fact object, or a dictionary representing a fact object, and returns that facts source as a string. If it fails to find any source, it returns 'None' as a string. 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
I tested the functionality with this test script.
```python
import asyncio
from app.objects.secondclass.c_fact import Fact
from app.utility.base_knowledge import BaseKnowledgeService

def test():
    test_fact = Fact('test', 'test value', source='123456')
    bks = BaseKnowledgeService()
    asyncio.run(bks._add_fact(test_fact)) # Add fact to knowledge service so we can test with dictionary input.
    factObjectTest = asyncio.run(bks._get_fact_origin(test_fact))
    print("Fact Source: {}".format(factObjectTest))

    # Given Fact criteria, it searches for related facts and gives us the source of the first one in the list. 
    dictObjectTest = asyncio.run(bks._get_fact_origin({"score": 1, "source": "123456"}))
    print("Fact Source: {}".format(dictObjectTest))

test()
```

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2021-07-09 14:45 UTC, wbooth requested changes
let's find a solution that doesn't require type checking for logic flow

2021-07-09 15:56 UTC, copsahl commented
> let's find a solution that doesn't require type checking for logic flow

I implemented a change to the function logic that I hope reflects what you were looking for. Let me know if it doesn't meet specifications. I tested it and it worked as expected.

2021-07-23 18:49 UTC, ArtificialErmine commented on app/utility/base_knowledge_svc.py
> +                    factOrigin = str(foundFacts[0].links[0].host)
This is being super pedantic, but this line (and the other on 87) both seem to be pretty darn similar to 78 and 80. Is there any way we could simplify these to reduce the duplication?

2021-08-04 18:05 UTC, wbooth commented on app/utility/base_knowledge_svc.py
> +        tempFact = fact
can you add a doctoring to this function so I can better understand what your objective is

2021-08-17 20:40 UTC, wbooth commented on app/utility/base_knowledge_svc.py
> +        tempFact = fact # Used so we don't overwrite the supplied fact
https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

2021-08-17 20:41 UTC, wbooth requested changes

2021-08-17 20:41 UTC, wbooth commented on app/utility/base_knowledge_svc.py
> +        return None # If all the above fails, return none.
please take a pass through this code and remove as many comments as possible. where you feel that a comment can't be removed move the code block to a function with a doc string / give the function a descriptive name

2021-08-18 20:55 UTC, ArtificialErmine commented
Closed in favor of https://github.com/mitre/caldera/pull/2231

2021-08-18 20:55 UTC, closed without merging