[VIRTS-2789] Adversary v2 API Pytests
mitre/caldera pull request #2247
Opened 2021-09-02 13:27 UTC by bleepbop

## Description
Added v2 API tests for the adversaries api.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Ensured that tests work for various versions of python by using tox.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

2021-09-14 12:39 UTC, uruwhy requested changes
If you can include the atomic ordering in the adversary payloads, that'd be great!

2021-09-14 13:05 UTC, uruwhy approved these changes

2021-09-16 14:29 UTC, uruwhy submitted a review, later dismissed

2021-09-28 13:52 UTC, clenk approved these changes
Looks Good To Me.

2021-09-30 13:42 UTC, uruwhy approved these changes
LGTM

2021-10-04 21:08 UTC, merged