Add plugin field to adversaries, abilities, and planners
mitre/caldera pull request #2345
Opened 2021-11-01 19:52 UTC by argaudreau

## Description

This PR adds a plugin field to adversaries, abilities, and planner objects. This field is helpful in parts of the UI for discoverability/traceability sake, and it will allow the atomic and stockpile plugin UIs to load without hanging up the whole server with an `os.walk()`.

Tests have also been updated to check for the new field and all were passing locally. There are some small changes to the UI as well to re-enable the atomic and stockpile plugins. These will have a separate PR shortly to make use of this new field.  

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

I made requests to the abilities, adversaries, and planner endpoints to ensure that the objects returned contained the "plugin" field with the appropriate plugin it came from. I also ran `pytest` locally and all tests passed.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2021-11-08 18:37 UTC, bleepbop requested changes
Everything looks good to me, but I'm having trouble seeing why `test_replace_source` is causing an error - I had fixed an issue with timestamps in another part of that test in #2328. I guess worst case scenario we could just pop the `created` key from the dumped objects before `assert source.display_schema.dump(source) == expected_replaced_source_dump`?

2021-11-10 17:36 UTC, argaudreau commented
@bleepbop I must've been behind master, just pulled it in and all checks are passing now.

2021-11-11 02:19 UTC, bleepbop approved these changes

2021-11-22 03:52 UTC, clenk reviewed
If a YAML file is added to `caldera/data/`, the `plugin` field will be the type of object. For example, I created a new ability in the GUI, which placed a new file in `data/abilities` so the `plugin` value is `abilities`. Is that intentional? A better value might be `data` or even `none` (since it didn't come from any plugin).

Should sources also have a plugin field?

Will there be followon PRs to display the plugin information in the UI? I'm thinking the ability modal, adversary tab, and fact sources tab.

2021-11-22 03:52 UTC, clenk commented on app/service/data_svc.py
> +            obj.plugin = filename.split('/')[1]
This will work because we don't need to support the server on Windows, otherwise I'd recommend using `pathlib` and `PurePath.parts` instead.

2021-11-23 14:14 UTC, argaudreau commented
> If a YAML file is added to `caldera/data/`, the `plugin` field will be the type of object. For example, I created a new ability in the GUI, which placed a new file in `data/abilities` so the `plugin` value is `abilities`. Is that intentional? A better value might be `data` or even `none` (since it didn't come from any plugin).

Great catch, I modified it so if any object comes from a path without a plugin, it defaults to an empty string.

> Should sources also have a plugin field?

Yes, I've added that as well.

> Will there be followon PRs to display the plugin information in the UI? I'm thinking the ability modal, adversary tab, and fact sources tab.

There are a couple queued up that will add the plugin field across the site.

2021-11-23 15:20 UTC, clenk commented on app/service/data_svc.py
> +                plugin = plugin_path[1] if 'plugins' in plugin_path else None
Might be worth pulling this out to its own function since the same code is used in `load_yaml_file()`

2021-11-23 16:36 UTC, bleepbop approved these changes

2021-11-23 16:47 UTC, bleepbop approved these changes
Tests failing due to an unrelated issue addressed by #2356, but everything looks good to me!

2021-11-23 17:41 UTC, clenk approved these changes
LGTM!

2021-11-29 20:30 UTC, merged