Add API docs for /operations and /operations{id} endpoints.
mitre/caldera pull request #2369
Opened 2021-11-22 22:57 UTC by CDJellen

## Description

Add API documentation for the `/operations` and `/operations/{id}` endpoints.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

This PR includes summaries and descriptions for the `/operations` and `/operations/{id}` endpoints in the Swagger UI.  The branch was tested by navigating to the Swagger documentation page and verifying that all summaries and descriptions rendered correctly, with proper formatting.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-11-23 17:49 UTC, bleepbop requested changes

2021-11-23 17:49 UTC, bleepbop commented on app/api/v2/handlers/operation_api.py
> +    @aiohttp_apispec.request_schema(OperationSchema(partial=True))
This is the only endpoint where this specific change needs to be made, but can you add back the `only=['state', 'autonomous', 'obfuscator']` to the `request_schema`? The `store()` method of `c_operation.py` is called whenever we issue a PATCH/update request, and the only fields that can be updated in that method are state, autonomous, and obfuscator

2021-11-23 17:49 UTC, bleepbop commented on app/api/v2/handlers/operation_api.py
> +                                      '`include` and `exclude` filters.')
For the endpoints that contain a parameter in the url (GET operation by ID, PATCH, PUT, and DELETE) you can add the following to the `aiohttp_apispec.docs` decorator to describe the url parameter:
```
parameters=[{
  'in': 'path',
  'name': 'id',
  'schema': {'type': 'string'},
  'required': 'true',
  'description': 'UUID of the Operation object to be retrieved.'
}],
```

2021-11-23 17:49 UTC, bleepbop commented on app/api/v2/handlers/operation_api.py
>      @aiohttp_apispec.response_schema(OperationSchema)
One last thing that might be nice to have is a description for the `response_schema` in every endpoint. While GET operation by ID, PUT, PATCH, and POST all return a single dumped Operation object, `GET /operations` and `DELETE /operations{id}` return a list of dumped objects and a 204 HTTP response code, respectively.

2021-11-24 15:47 UTC, elegantmoose approved these changes
LGTM as long as @bleepbop comments are addressed.

2021-11-30 14:44 UTC, elegantmoose submitted a review, later dismissed

2021-12-02 13:04 UTC, bleepbop commented on app/api/v2/handlers/operation_api.py
> +    @aiohttp_apispec.response_schema(OperationSchema(partial=True, only=['state', 'autonomous', 'obfuscator']),
I think the `only=['state', 'autonomous', 'obfuscator']` was accidentally added to this endpoint - can you remove that from this endpoint, and add that to the `response_schema` for `update_operation()`?

2021-12-02 13:06 UTC, bleepbop commented on app/api/v2/handlers/operation_api.py
> +    @aiohttp_apispec.request_schema(LinkSchema(partial=True))
I don't think that these are part of your ticket, but could you add back `only=['command', 'status']` just for this endpoint?

2021-12-02 13:08 UTC, bleepbop requested changes
Just a few tiny changes and it should be good to go!

2021-12-02 16:31 UTC, CDJellen commented
Thank you for your review Ben, I've made the changes in the latest commit.

2021-12-02 16:49 UTC, bleepbop commented on app/api/v2/handlers/operation_api.py
> +    @aiohttp_apispec.response_schema(OperationSchema(partial=True, only=['state', 'autonomous', 'obfuscator']),
Sorry one last tiny change - can you move `only=['state', 'autonomous', 'obfuscator']` into the `request_schema` for this endpoint instead? I think this was accidentally added to the `response_schema`

2021-12-02 16:51 UTC, bleepbop commented on app/api/v2/handlers/operation_api.py
> -                                                       '"executor.command" is expected to be unencoded.')
Can you add this summary back for this endpoint?

2021-12-02 17:39 UTC, bleepbop approved these changes

2021-12-02 18:14 UTC, elegantmoose approved these changes

2021-12-03 15:57 UTC, elegantmoose commented
@wbooth - I think this PR is gtg if you want to override the lagging CI.

2021-12-13 18:45 UTC, wbooth approved these changes

2021-12-13 22:59 UTC, merged