Add plugin apidocs details
mitre/caldera pull request #2371
Opened 2021-11-23 18:56 UTC by argaudreau

## Description

Adds more information to the swagger documentation for plugin endpoints.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Swagger documentation is updated with new information.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-11-23 20:51 UTC, bleepbop requested changes
Looks good! This is a bit redundant, but just for consistency with the other endpoints, can you add an `aiohttp_apispec.response` `description` for these? It could just be something like "Returns a list of all Plugin objects dumped in PluginSchema format."

2021-11-27 06:40 UTC, iguannalin approved these changes
lgtm!

2021-11-29 17:37 UTC, argaudreau commented
> Looks good! This is a bit redundant, but just for consistency with the other endpoints, can you add an `aiohttp_apispec.response` `description` for these? It could just be something like "Returns a list of all Plugin objects dumped in PluginSchema format."

Makes sense, added a description field there!

2021-12-01 15:55 UTC, bleepbop approved these changes

2021-12-01 19:25 UTC, merged