Fix event_logs download functionality
mitre/caldera pull request #2373
Opened 2021-11-26 21:31 UTC by heatonk

## Description

Functionality was previously listed but not working, as mentioned in issue @2329. This fixes @2329 by creating another function that calls the correct API endpoint.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Verified solution by running locally and downloading event logs and reports from test operations.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-11-30 14:46 UTC, elegantmoose commented
Addresses #2329

2021-11-30 20:08 UTC, elegantmoose approved these changes

2021-11-30 21:40 UTC, iguannalin requested changes
Hi @heatonk, I think this file could be reduced a bit, if all that's changing is the API endpoint.

```
downloadInfo(formatType) {
    const endpoint = formatType === 'full-report' ? 'report' : formatType;
    apiV2('POST', `${this.ENDPOINT}/${this.selectedOperationID}/${endpoint}`, { enable_agent_output: this.isAgentOutputSelected })
        .then((res) => {
            this.createDownloadReport(res, `${this.selectedOperation.name}_${formatType}`);
        })
        .catch(() => toast(`Error generating operation ${formatType.replace('-', ' ')}`));
},

downloadCSV() {...},

handleDownload() {
    if (this.selectedReportType === 'full-report') this.downloadInfo('full-report');
    else if (this.selectedReportType === 'event-logs') this.downloadInfo('event-logs');
    else if (this.selectedReportType === 'csv') this.downloadCSV();
},
```

2021-12-01 15:18 UTC, iguannalin approved these changes
Looks good! I'll suggest ~~making sure to pull the latest changes from the master `operations.html` (i.e. I see there's a console error for operation that has been fixed but is still popping up in this branch's ver.), and~~ some linting to match the spacing with the rest of the functions.

2021-12-01 21:09 UTC, elegantmoose approved these changes

2021-12-02 18:12 UTC, merged