Add relationships API documentation
mitre/caldera pull request #2383
Opened 2021-12-06 18:02 UTC by argaudreau

## Description

This PR adds apispecs to Relationship POST, PATCH, and DELETE API endpoints.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

All descriptions and summaries appear in Swagger documentation.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2021-12-07 13:51 UTC, bleepbop requested changes
Just two small changes - unlike the PUT/PATCH/DELETE endpoints in the rest of the v2 API, `delete_relationships` and `update_relationships` here don't accept some sort of UUID in the URL to update a specific relationship. Instead everything is updated/replaced/deleted by criteria specified in the payload, so multiple relationships could be affected. If you could just add a comment in those two endpoint descriptions about how we use fields as criteria for selecting potentially multiple relationships, that would be great!

2021-12-08 20:39 UTC, argaudreau commented
Good point @bleepbop, I've made those descriptions more clear about that.

2021-12-09 02:13 UTC, bleepbop approved these changes

2021-12-09 14:58 UTC, iguannalin approved these changes

2021-12-10 14:36 UTC, merged