Documentation for /operations/{id}/potential-links and /operations/{i…
mitre/caldera pull request #2404
Opened 2021-12-16 18:40 UTC by djlawren

…d}/links/{link_id}/result

## Description

Added API documentation for `GET /api/v2/operations/{id}/links/{link_id}/result`, `POST /api/v2/operations/{id}/potential-links`, and `GET /api/v2/operations/{id}/potential-links`.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

I navigated to the documentation web page and checked that the new content added appeared as intended.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-12-17 16:17 UTC, bleepbop commented on app/api/v2/handlers/operation_api.py
> +                          summary='Retrieve links for an operation.',
This might be a little confusing because we also have a GET /links endpoint - can you change this to "Retrieve potential links for an operation"?

2021-12-17 16:19 UTC, bleepbop commented on app/api/v2/handlers/operation_api.py
> +                                     description='Response contains a completed Link object.')
This is a bit nitpicky but the response will just be the newly assigned Link object, it may not necessarily be completed just yet

2021-12-17 16:19 UTC, bleepbop requested changes
Looks good! just two small changes

2021-12-17 19:18 UTC, elegantmoose submitted a review, later dismissed

2021-12-20 19:57 UTC, bleepbop approved these changes

2021-12-20 20:50 UTC, elegantmoose approved these changes

2021-12-21 17:41 UTC, elegantmoose approved these changes

2021-12-21 18:05 UTC, elegantmoose commented
@wbooth - ready to merge

2022-01-04 13:15 UTC, merged