VIRTS 3201-3203 API v2 Agent Documentation
mitre/caldera pull request #2405
Opened 2021-12-16 20:02 UTC by ddavila54

## Description

Documentation for API v2 docs (Agent HEAD, GET, PATCH)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Swagger UI Docs working.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2021-12-17 16:22 UTC, bleepbop commented on app/api/v2/handlers/agent_api.py
> +                          summary="Retrieve Agent Information",
Just to make sure this is different from the `get_agents` description, can you change this summary to "Retrieve Agent by paw"?

2021-12-17 16:24 UTC, bleepbop commented on app/api/v2/handlers/agent_api.py
> +    @aiohttp_apispec.response_schema(AgentSchema(only=[]), description="Returns JSON response with updated Agent fields")
This `only=[]` can be removed from the  AgentSchema here

2021-12-17 16:25 UTC, bleepbop requested changes
Two quick changes and it should be good to go!

2021-12-17 17:56 UTC, ArtificialErmine approved these changes
LGTM

2021-12-17 18:06 UTC, bleepbop commented on app/api/v2/handlers/agent_api.py
> +    @aiohttp_apispec.response_schema(AgentSchema(only=[]), description="Returns JSON response with specified Agent "
Sorry missed this before, but this `only=[]` can be removed as well

2021-12-21 13:41 UTC, bleepbop approved these changes

2021-12-22 16:39 UTC, ArtificialErmine approved these changes
LGTM

2021-12-22 16:45 UTC, merged