UI feature auto complete
mitre/caldera pull request #2447
Opened 2022-01-19 22:16 UTC by iguannalin

## Description

Updated/Added auto-complete feature to agents, adversaries and abilities page to search for abilities 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-02-01 19:02 UTC, argaudreau requested changes
Great idea moving the dropdown styles to shared.css so it's really easy to add if we need it anywhere else in the future. Just a couple of tweaks to make but overall looks good!

2022-02-01 19:02 UTC, argaudreau commented on templates/profiles.html
> +                                <div class="control auto-complete">
The autocomplete on the search works great here! I'd add an autocomplete to the tactic, technique Id and name just like I suggested for the abilities page

2022-02-04 15:20 UTC, argaudreau requested changes
Just a couple more things and we'll be good to merge!

2022-02-04 15:20 UTC, argaudreau commented on templates/abilities.html
> +                                        <div class="control auto-complete" x-data="{focusSearchResults: true}">
We can remove the search from this modal since there's a search on the page for it.

2022-02-09 15:46 UTC, argaudreau commented on templates/abilities.html
> +                                            <input class="input is-small" x-bind:class="{ 'is-danger': fieldErrors.includes('tactic') }" x-model="selectedAbility.tactic" x-on:keyup="searchForAutoFill
Scratch that -- I'm no longer seeing this behavior

2022-02-15 15:49 UTC, argaudreau approved these changes

2022-02-16 03:10 UTC, mshkolnik22 approved these changes
Looks good, auto complete feature works.

2022-02-16 14:30 UTC, merged