Added space above Cancel Changes and set min to zero in Objectives
mitre/caldera pull request #2535
Opened 2022-03-30 14:27 UTC by mshkolnik22

## Description

Added space above Cancel Changes button and set min to zero to Goals in Objectives.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-03-31 19:15 UTC, argaudreau requested changes
One small change and it's good to merge!

2022-04-04 21:08 UTC, iguannalin requested changes
Your changes LGTM! I found an unrelated bug, maybe we can merge it into this PR as it is a one line fix? https://github.com/mitre/caldera/pull/2538

2022-04-21 15:07 UTC, mshkolnik22 commented on templates/objectives.html
> +                <!-- <button class="button is-small is-flex is-flex-end" @click="cancelEditing()" x-show="isEditing">
Done!

2022-04-21 15:28 UTC, iguannalin approved these changes

2022-04-27 12:58 UTC, argaudreau approved these changes

2022-04-27 12:58 UTC, merged