Details added to existing operations
mitre/caldera pull request #2558
Opened 2022-04-29 13:13 UTC by mshkolnik22

## Description

User is able to see details of an existing operation

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

Self check in a browser.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-05-02 17:53 UTC, argaudreau requested changes
I'd like to see more details about the operation, specifically all the settings used in the Create Operation window, like:
* Jitter
* Fact source
* Group
* Parser
* Auto close
* Visibility
* etc...
This kind of info would be best placed in a modal or popup, which would be opened via a button since space is limited on the line with the operation name. I'd recommend taking a look at what is returned from the GET request to get the current operation to see what kind of metadata it returns so you can get an idea of what to display.

2022-06-23 13:30 UTC, argaudreau requested changes
Just one small change, but otherwise looks good to me!

2022-06-23 16:03 UTC, mshkolnik22 commented on templates/operations.html
> +                    <span x-text="'Current Operation:  ' + selectedOperation.name + '  |  ' + selectedOperation.adversary.name + '  |  ' + selectedOperation.source.name" ></span>
implemented.

2022-06-27 00:16 UTC, mshkolnik22 commented
I made all the requested changes. Can you please take another look?

2022-06-27 18:35 UTC, argaudreau requested changes
The modal appears off in Firefox:
![Screen Shot 2022-06-27 at 2 31 48 PM](https://user-images.githubusercontent.com/6034483/176011390-aeb0abf4-9fcf-46e5-9cab-b2f0b079d593.png)

The More Details button might look better to the left of the download button, and if we move it there renaming it to "Operation Details" would be more explicit. The button as-is seems kind of jarring next to the text, so moving it to the button row below that would clean it up.

2022-06-28 15:01 UTC, ZacharyLPalmer reviewed
Concur with adam on the button moving inline with download/delete. I looked at the modal in firefox and it didn't look off, so not sure why it's showing up like that for Adam. I would also say that having the operation name in line with the other information might make more sense, but I think it works either way.

2022-07-13 19:13 UTC, argaudreau approved these changes

2022-07-28 14:49 UTC, ZacharyLPalmer approved these changes
Looks good!

2022-07-28 15:14 UTC, merged