add helper method for updating ignored links; use chain data to provi…
mitre/caldera pull request #2822
Opened 2023-09-23 17:44 UTC by bleepbop

…de list of potential skipped abilities

## Description

(insert summary)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-09-26 16:41 UTC, elegantmoose approved these changes

2023-10-02 16:54 UTC, clenk approved these changes

2023-10-02 16:56 UTC, clenk requested changes
Fix failing test:
```
tests/objects/test_operation.py:595: in test_add_ignored_link
    op.add_ignored_link(test_link)
app/objects/c_operation.py:260: in add_ignored_link
    self.ignored_links.add(link_id)
E   TypeError: unhashable type: 'Link'
```

2023-10-13 19:00 UTC, clenk approved these changes
Nice!

2023-10-16 19:42 UTC, elegantmoose approved these changes
@bleepbop Nice work.

2023-10-16 19:44 UTC, merged