Refactor Docker setup, follow best-practices in containerization and make caldera easier to deploy
mitre/caldera pull request #3114
Opened 2024-12-26 17:12 UTC by daw1012345

## Description

This project is currently quite difficult to get working. This is one of (at least) three pull requests intended to make caldera simpler to deploy or get running locally. Docker is a great tool for this, and should be the easiest and quickest deployment option.

Unfortunately, the current Dockerfile doesn't even build (due to an outdated version of Ubuntu).
This PR:
- Updates the Dockerfile to use a staged build to compile the UI and copies it over to the final container. This avoids the dance of installing node and npm, building the UI, then removing node and npm.
- Ensures that previous builds of caldera do not pollute the build within the container. For example, if caldera was ever compiled outside of Docker (especially the UI), it will not be recompiled in the container. This can cause a large headache, for example when the Docker build does not re-build the UI when the VITE_BASE_URL was changed.
- Containers should contain all basic requirements for all of the functionality to work. For example - if a container is compiled without emu support and then published to DockerHub, a user will not be able to easily get all the dependencies into the container (without modifying the Dockerfile and building it themselves). This PR ensures this is the case.
- The emu and atomic plugins depend on large submodules to work, but are capable of fetching them when they are enabled. This PR introduces two flavours of images - *slim* and *full*. The *full* (default) flavor contains said submodules to allow the container to work in environments without an internet connection, while the *slim* flavour disables the plugins and only fetches the submodules when they are enabled.
- Modify the workflow to build and push both *slim* and *full* images to GHCR (tagged appropriately).
- Adds a dependency on `setuptools` to work with recent versions of Python3
- Makes Docker the recommended deployment option in the README

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [NOT RELEVANT] I have added tests that prove my fix is effective or that my feature works

2024-12-27 22:22 UTC, rfulwell commented
These changes are super interesting and I look forward to going through them in detail! 🚀

In the meantime, here's the minimal fix for the Docker build which was approved and just waiting on a merge:
https://github.com/mitre/caldera/pull/3099 @daw1012345

2024-12-27 22:26 UTC, rfulwell commented
> Docker is a great tool for [deployment], and should be the easiest and quickest deployment option.

💯

Thank you for tackling these changes! I fully agree that this project will be much more useful when Docker deployment is trivial. 👍

2025-01-05 09:59 UTC, daw1012345 commented
Thanks @rfulwell. I made a few additional change to the Docker setup, I was wondering if you could test it yourself as well to make sure everything works? I am by no means a caldera power user and would like to make sure these changes don't break anything.

2025-01-05 09:59 UTC, daw1012345 commented
And thank you for the original PR fixing the outdated Ubuntu version in the Dockerfile, hope that gets merged quickly as well.

2025-01-09 18:41 UTC, elegantmoose commented
On our queue.

2025-02-27 01:36 UTC, fstarnaud commented on Dockerfile
> +FROM node:23 as ui-build
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 3)

2025-02-27 01:37 UTC, fstarnaud commented on Dockerfile
> +FROM debian:bookworm-slim as runtime
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 13)

2025-03-12 02:33 UTC, endiz commented
While I don't use docker for this project, I think quite a lot of people do to quickly get started. This PR would be a great service to the community.

2025-03-12 15:26 UTC, elegantmoose commented
@endiz Yep, @uruwhy  is gonna look at this one once he has a minute.

2025-03-12 18:36 UTC, uruwhy commented on Dockerfile
> +# The slim variant excludes some dependencies of *emu* and *slim* that can be downloaded on-demand if needed
```suggestion
# The slim variant excludes some dependencies of *emu* and *atomic* that can be downloaded on-demand if needed
```

2025-03-12 18:37 UTC, uruwhy commented on Dockerfile
> +        echo "Invalid Docker build-arg!"; \
```suggestion
        echo "Invalid Docker build-arg for VARIANT! Please provide either \"full\" or \"slim\"."; \
```

2025-03-12 19:17 UTC, uruwhy commented on Dockerfile
> +RUN pip3 install --break-system-packages --no-cache-dir -r requirements.txt
thoughts on installing packages within a virtual env?

2025-03-12 19:23 UTC, uruwhy commented on Dockerfile
> +    pip3 install --break-system-packages -r requirements.txt
thoughts on installing packages within a virtual env?

2025-03-12 20:00 UTC, daw1012345 commented on Dockerfile
> +RUN pip3 install --break-system-packages --no-cache-dir -r requirements.txt
This was a conscious choice. We already are in a Docker container, we don't have to worry about polluting anything.

2025-03-13 17:10 UTC, uruwhy commented
some minor merge conflicts and a couple suggestions to get rid of the warning messages, and should be good to go

2025-03-13 17:10 UTC, uruwhy requested changes
some minor merge conflicts and a couple suggestions to get rid of the warning messages, and should be good to go

2025-03-18 18:03 UTC, uruwhy approved these changes

2025-03-18 18:58 UTC, elegantmoose commented
@uruwhy approved and this is now on queue. Will look at asap.

2025-03-24 16:45 UTC, daw1012345 commented
@elegantmoose I had no issues using a newer version of Debian>

Regarding your second point: it prints out the credentials on first run already (at the very top).

2025-03-24 16:57 UTC, elegantmoose commented
I dont follow. You mean like where the config file is?

2025-03-24 17:03 UTC, daw1012345 commented
> I dont follow. You mean like where the config file is?

No, it prints out the generated credentials.

For example: 
![image](https://github.com/user-attachments/assets/519fdefe-305d-4790-9a1f-cc9bf9f7f5b5)

(This is a sample container, the random credentials are not sensitive)

2025-03-24 17:35 UTC, elegantmoose commented
weird, not seeing that at all. Let me investigate.

2025-03-24 18:22 UTC, elegantmoose commented
@daw1012345 Alright cool, working clean now. 

One request, could be we put like `ENV COLUMNS=120` in the Dockerfile so that the Caldera log output is not too narrow?

Impetus: When I went to copy the credential password from the log output, it breaks over multiple lines and has large gap spaces, so I had to paste into notepad, remove newlines and return then re copy, then paste into Caldera.

2025-03-24 18:43 UTC, elegantmoose submitted a review, later dismissed

2025-03-24 20:36 UTC, daw1012345 commented
@elegantmoose The better approach would be to encourage the users to run it in proper TTY mode (`-it` flag).

2025-03-25 01:46 UTC, elegantmoose approved these changes

2025-03-25 01:47 UTC, merged

2025-03-25 01:48 UTC, elegantmoose commented
TY @daw1012345 . 👏